Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.10"
  config.vm.network :forwarded_port, guest: 8443, host: 8443 
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision :shell, path: "dderlstrap.sh", privileged: false
  config.vm.provision :shell, path: "dderlup.sh", run: "always", privileged: false
end
